apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmpe272-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cmpe272
  template:
    metadata:
      labels:
        app: cmpe272
    spec:
      containers:
      - name: cmpe272
        image: cmpe272:latest          
        imagePullPolicy: IfNotPresent  
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        ports:
        - containerPort: 8000
