apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmpe272-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cmpe272
  template:
    metadata:
      labels:
        app: cmpe272
    spec:
      containers:
      - name: cmpe272
        image: docker.io/alxhuang001/cmpe272
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: cmpe272-service
spec:
  selector:
    app: cmpe272
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer
